name: adv_gpu_yolov5
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pillow=9.0.0
  - cudatoolkit=11.3
  - cudnn=8.2.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1

  - pip:
    # YOLOv5 and dependencies
    - yolov5==7.0.12
    - numpy==1.22.4
    - scipy==1.9.1
    - opencv-python==4.6.0.66
    - matplotlib==3.5.3
    - pandas==1.4.4
    - tqdm==4.64.1
    - seaborn==0.11.2
    - pyyaml==6.0
    - requests==2.28.1

    # Flask ecosystem
    - flask==2.0.3
    - werkzeug==2.0.3
    - jinja2==3.0.3
    - itsdangerous==2.0.1
    - flask-cors==3.0.10    
    
    # Web sockets
    - eventlet==0.29.1
    - flask-socketio==4.3.1
    - python-socketio==4.6.0
    - python-engineio==3.13.2
    - websocket-client==1.1.0